"""removed autoincremente table users

Revision ID: 1c7a1ec39c07
Revises: e1a28ce049c5
Create Date: 2023-09-10 15:46:34.435155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c7a1ec39c07'
down_revision: Union[str, None] = 'e1a28ce049c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
